# Generated by Django 2.2.16 on 2022-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationemailkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationemailkey',
            name='id',
        ),
        migrations.AlterField(
            model_name='verificationemailkey',
            name='key',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
