# Generated by Django 2.2.16 on 2022-08-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20220802_0133'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='uniq_review',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('titles', 'author'), name='unique_titles_author'),
        ),
    ]
